import peerDepsExternal from 'rollup-plugin-peer-deps-external';
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "@rollup/plugin-typescript";
import dts from "rollup-plugin-dts";
import packageJson from "./package.json" with { type: "json" };

export default [
  {
    input: "src/index.ts",
    output: [
      {
        file: packageJson.main,
        format: "cjs",
        sourcemap: true,
        name: "formsy-react-mui",
      },
      {
        file: packageJson.module,
        format: "esm",
        sourcemap: true
      },
    ],
    plugins: [
      peerDepsExternal(),
      resolve(), 
      commonjs(),
      typescript({
        tsconfig: "./tsconfig.json",
        exclude: ["**/__tests__/**", "**/*.test.ts", "**/*.stories.tsx"],
      }),
    ]
  },
  // Bundle TypeScript declaration files (.d.ts)
  {
    input: "dist/types/index.d.ts", // Input generated by first build step (or tsc)
    output: [{ file: packageJson.types, format: "esm" }], // Output single d.ts file
    plugins: [dts()], // Use rollup-plugin-dts
    external: [/\.css$/], // Ignore CSS imports in declaration files
  },
];
